#define TOP_LEFT_WINDOW 0x94F0
#define TOP_CENTER_WINDOW 0x94F1
#define TOP_RIGHT_WINDOW 0x94F2
#define MIDDLE_LEFT_WINDOW 0x94F3
#define MIDDLE_CENTER_WINDOW 0x94F4
#define MIDDLE_RIGHT_WINDOW 0x94F5
#define BOTTOM_LEFT_WINDOW 0x94F6
#define BOTTOM_CENTER_WINDOW 0x94F7
#define BOTTOM_RIGHT_WINDOW 0x94F8

const int top_10[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_RIGHT_WINDOW
};

const int mid_10[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,MIDDLE_RIGHT_WINDOW
};

const int bot_10[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_RIGHT_WINDOW
};

const int top_12[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW,TOP_RIGHT_WINDOW
};

const int mid_12[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW,MIDDLE_RIGHT_WINDOW
};

const int bot_12[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW,BOTTOM_RIGHT_WINDOW
};

const int top_14[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_CENTER_WINDOW, 
        TOP_CENTER_WINDOW,TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,TOP_RIGHT_WINDOW
};

const int mid_14[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,MIDDLE_RIGHT_WINDOW
};

const int bot_14[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW,BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_RIGHT_WINDOW
};

const int top_16[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_RIGHT_WINDOW
};

const int mid_16[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_RIGHT_WINDOW
};

const int bot_16[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_RIGHT_WINDOW
};

const int top_18[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_RIGHT_WINDOW
};

const int mid_18[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_RIGHT_WINDOW
};

const int bot_18[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_RIGHT_WINDOW
};

const int top_22[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW,TOP_RIGHT_WINDOW
};

const int mid_22[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW,MIDDLE_RIGHT_WINDOW
};

const int bot_22[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_RIGHT_WINDOW
};

const int top_32[] = {
        TOP_LEFT_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_CENTER_WINDOW,
        TOP_CENTER_WINDOW, TOP_CENTER_WINDOW, TOP_RIGHT_WINDOW
};

const int mid_32[] = {
        MIDDLE_LEFT_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW,
        MIDDLE_CENTER_WINDOW, MIDDLE_CENTER_WINDOW, MIDDLE_RIGHT_WINDOW
};

const int bot_32[] = {
        BOTTOM_LEFT_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW,
        BOTTOM_CENTER_WINDOW, BOTTOM_CENTER_WINDOW, BOTTOM_RIGHT_WINDOW
};

void window_10(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_10,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_10,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_10,row_x);
}

void window_14(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_14,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_14,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_14,row_x);
}

void window_16(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_16,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_16,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_16,row_x);
}

void window_18(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_18,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_18,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_18,row_x);
}

void window_22(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_22,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_22,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_22,row_x);
}

void window_32(int vaddr, char row_x, char row_y )
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_32,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_32,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_32,row_x);
}

void window_12(int vaddr, char row_x, char row_y)
{
  char i;
  int offset;

  offset = 0;
  load_vram(vaddr+offset,top_12,row_x);
  for(i=0; i<row_y-2; i++)
  {
    offset+=screen_dimensions;
    load_vram(vaddr+offset,mid_12,row_x);
  }
  offset+=screen_dimensions;
  load_vram(vaddr+offset,bot_12,row_x);
}
