; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.99-c266d57, 2018-07-07)
; on Sat Oct 02 12:00:01 2021
;

HUC	= 1
HAVE_INIT = 1
                                                            
SMALL	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc ___compact
	__pushw
	__ldw_s	2
	__stw	____compact_lend-6
	__stwi	____compact_lend-2, 0
LL2:

	__ldw_s	2
	__stw	<__ptr
	__ldwp	__ptr
	__stw	____compact_lend-4
	__tstw
	__lbeq	LL3
	__ldw	____compact_lend-4
	__andwi	1
	__tstw
	__lbeq	LL4
	__ldw	____compact_lend-2
	__cmpwi_ne	0
	__lbeq	LL5
	__ldw	____compact_lend-6
	__stw	<__ptr
	__ldw	____compact_lend-2
	__stwp	__ptr
	__ldw	____compact_lend-2
	__stw	<__temp
	__ldw_s	0
	  jsr	ugezp
	__lbeqn	LL6
	__ldw	____compact_lend-6
	__lbra	LL1
LL6:

LL5:

	__stwz	____compact_lend-2
	__ldw_s	2
	__stw	____compact_lend-8
	__pushw
	__ldw	____compact_lend-4
	__andwi	65534
	__aslw
	__addws
	__stw_s	2
	__stw	____compact_lend-6
	__lbra	LL7
LL4:

	__ldw	____compact_lend-2
	__addw	____compact_lend-4
	__stw	____compact_lend-2
	__ldw_s	2
	__stw	____compact_lend-8
	__pushw
	__ldw	____compact_lend-4
	__aslw
	__addws
	__stw_s	2
LL7:

	__lbra	LL2
LL3:

	__ldw	____compact_lend-2
	__cmpwi_ne	0
	__lbeq	LL8
	__ldw	____compact_lend-6
	__stw	<__ptr
	__ldw	____compact_lend-2
	__stwp	__ptr
	__ldw	____compact_lend-2
	__stw	<__temp
	__ldw_s	0
	  jsr	ugezp
	__lbeqn	LL9
	__ldw	____compact_lend-6
	__lbran	LL1
LL9:

LL8:

	__ldwi	0
LL1:

	__addmi	4,__stack
	  rts
	.endp

	.proc _free
	__pushw
	__ldw_s	0
	__tstw
	__lbeqn	LL11
	__ldw_s	0
	__subwi	4
	__stw	__free_lend-2
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__andwi	65534
	__stwps
LL11:

LL10:

	__addmi	2,__stack
	  rts
	.endp

	.proc _malloc
	__pushw
	__ldw_s	0
	__cmpwi_eq	0
	__lbeqn	LL13
	__ldwi	0
	__lbra	LL12
LL13:

	__ldw_s	0
	__addwi	5
	__stw_s	0
	__lsrwi	2
	__stw_s	0
	__aslwi	2
	__stw_s	0
	__ldw	_msys
	__cmpwi_eq	0
	__lbnen	LL15
	__ldw_s	0
	__pushw
	__ldw	_msys
	__stw	<__ptr
	__ldwp	__ptr
	  jsr	ugt
LL15:

	__tstw
	__lbeq	LL14
	__ldw	_msys+2
	__pushw
	__ldw_s	2
	  call	___compact
	__stw	_msys
	__cmpwi_eq	0
	__lbeqn	LL16
	__ldwi	0
	__lbra	LL12
LL16:

LL14:

	__ldw	_msys
	__stw	__malloc_lend-4
	__ldw	_msys
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__malloc_lend-2
	__pushw
	__ldw_s	2
	__addwi	2
	  jsr	uge
	__lbeq	LL17
	__ldw	__malloc_lend-4
	__stw	__malloc_lend-6
	__pushw
	__ldw_s	2
	__aslw
	__addws
	__stw	_msys
	__pushw
	__ldw	__malloc_lend-2
	__pushw
	__ldw_s	4
	__subws
	__stwps
	__lbran	LL18
LL17:

	__stwz	_msys
	__ldw	__malloc_lend-2
	__stw_s	0
LL18:

	__ldw	__malloc_lend-4
	__pushw
	__ldw_s	2
	__orwi	1
	__stwps
	__ldw	__malloc_lend-4
	__stw	__malloc_lend-6
	__addwi	4
LL12:

	__addmi	2,__stack
	  rts
	.endp
	.data
	.bss
	__malloc_loc: .ds 6
	__malloc_lend:
	.code

	.proc ___malloc_init
	__pushw
	__ldw_s	0
	__lsrwi	2
	__stw_s	0
	__aslwi	2
	__stw_s	0
	__ldw_s	2
	__stw	_msys+2
	__stw	_msys
	__pushw
	__ldw	_msys+2
	__pushw
	__ldw_s	4
	__subwi	2
	__stwps
	__stwps
LL19:

	__addmi	4,__stack
	  rts
	.endp

	.proc ___malloc_init2
	__ldwi	__heap_start
	__pushw
	__ldwi	1024
	  call	___malloc_init
LL20:

	  rts
	.endp

	.proc _compact
	__ldw	_msys+2
	__pushw
	__ldwi	65535
	  call	___compact
	__stw	_msys
LL21:

	  rts
	.endp

	.proc _realloc
	__pushw
	__ldw_s	0
	  call	_malloc
	__stw	__realloc_lend-2
	__ldw	__realloc_lend-2
	__stw	__di
	__ldw_s	2
	__stw	__si
	__ldw_s	0
	  call	_memcpy.3
	__ldw_s	2
	  call	_free
	__ldw	__realloc_lend-2
LL22:

	__addmi	4,__stack
	  rts
	.endp
	.data
	.bss
	__realloc_loc: .ds 2
	__realloc_lend:
	.code

	.data
_testpal:
	.incpal "map/bgmap.tiles.pcx"
	.code
	.data
_testtiles:
	.inctile "map/bgmap.tiles.pcx"
	.code
	.data
_testtable:
	.inctilepal "map/bgmap.tiles.pcx"
	.code
	.data
_testmap:
	.incbin "map/bgmap.Untitled 1.layer-Layer 1.map001.stm"

	.code
	.data
_sold:
	.incspr "map/sprites/soldierorg.pcx",0,0,2,8
	.code
	.data
_attack:
	.incspr "map/sprites/soldierorg.pcx",0,128,2,8
	.code
	.data
_soldierpal:
	.incpal "map/sprites/soldier.pcx"
	.code
	.proc _main
	__stwi	__main_lend-2, 160
	__stwi	__main_lend-4, 128
	__stwi	__main_lend-6, 0
	__stwi	__main_lend-8, 0
	__stwi	__main_lend-10, 32
	__stwi	__main_lend-12, 0
	__stwi	__main_lend-16, 0
	__stwi	__main_lend-18, 0
	__stwz	__main_lend-20
	__stwi	__main_lend-28, 2
	__stwi	__main_lend-30, 1
	__stwz	__main_lend-24
	__stwi	__main_lend-22, _armyOne
LL24:

	__ldw	__main_lend-24
	__stw	<__temp
	__ldwi	4
	  jsr	ltzp
	__lbnen	LL26
	__lbra	LL27
LL25:

	incw	__main_lend-24
	__ldw	__main_lend-22
	__addwi	18
	__stw	__main_lend-22
	__lbra	LL24
LL26:

	__ldw	__main_lend-24
	__addw	__main_lend-28
	__aslwi	7
	__addw	__main_lend-30
	__stw	__main_lend-26
	__ldw	__main_lend-22
	__addwi	4
	__stw	<__ptr
	__ldw	__main_lend-26
	__stwp	__ptr
	__ldw	__main_lend-22
	__addwi	17
	__stbip	1
	__ldw	__main_lend-22
	__addwi	8
	__stw	<__ptr
	__ldw	__main_lend-24
	__stwp	__ptr
	__ldwi	_grid
	__addw	__main_lend-26
	__stbip	1
	__ldw	__main_lend-26
	__addwi	1
	__addwi_sym	_grid
	__stbip	3
	__ldw	__main_lend-26
	__subwi	1
	__addwi_sym	_grid
	__stbip	3
	__lbra	LL25
LL27:

	__stwi	__main_lend-28, 5
	__stwi	__main_lend-30, 5
	__stwz	__main_lend-24
	__stwi	__main_lend-22, _armyTwo
LL28:

	__ldw	__main_lend-24
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
	__lbnen	LL30
	__lbra	LL31
LL29:

	incw	__main_lend-24
	__ldw	__main_lend-22
	__addwi	18
	__stw	__main_lend-22
	__lbra	LL28
LL30:

	__ldw	__main_lend-24
	__addw	__main_lend-28
	__aslwi	7
	__addw	__main_lend-30
	__stw	__main_lend-26
	__ldw	__main_lend-22
	__addwi	4
	__stw	<__ptr
	__ldw	__main_lend-26
	__stwp	__ptr
	__ldw	__main_lend-22
	__addwi	17
	__stbip	1
	__ldw	__main_lend-22
	__addwi	8
	__stw	<__ptr
	__ldw	__main_lend-24
	__stwp	__ptr
	__ldwi	_grid
	__addw	__main_lend-26
	__stbip	2
	__lbra	LL29
LL31:

	__stwi	__main_lend-26, 0
	  call	_disp_off
	__ldwi	5
	  call	_set_screen_size
	  call	_cls
	  call	_init_satb
	__ldwi	16
	  stx	__al
	__farptr	_soldierpal,__bl,__si
	__ldwi	1
	  stx	__cl
	  call	_load_palette.3
	__stwi	__main_lend-22, _armyOne
	__ldw	__main_lend-22
	__pushw
	__ldwi	1024
	__pushw
	__ldwi	20480
	__pushw
	__ldwi	2
	__pushw
	__ldwi	1
	__pushw
	__ldwi	4
	__pushw
	__ldwi	0
	  call	_populate_army
	__ldwi	17
	  stx	__al
	__farptr	_soldierpal,__bl,__si
	__ldwi	2
	  stx	__cl
	  call	_load_palette.3
	__stwi	__main_lend-22, _armyTwo
	__ldw	__main_lend-22
	__pushw
	__ldwi	1024
	__pushw
	__ldwi	20480
	__pushw
	__ldwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	2
	__pushw
	__ldwi	4
	  call	_populate_army
	  call	_satb_update
	__ldwi	1
	__stw	color_reg
	__ldwi	7
	  stx	__al
	__ldwi	7
	  stx	__ah
	__ldwi	7
	  call	_set_color_rgb.4
	__ldwi	1
	  stx	__al
	__ldwi	0
	  call	_set_font_color.2
	__ldwi	0
	  call	_set_font_pal
	  call	_load_default_font
	  call	_disp_on
	  call	_vsync
LL32:

LL33:

LL34:

	  call	_tick
	  call	_vsync
	  call	_controls
	__stwz	__main_lend-14
	__stwi	__main_lend-22, _armyOne
LL36:

	__ldw	__main_lend-14
	__stw	<__temp
	__ldwi	4
	  jsr	ltzp
	__lbnen	LL38
	__lbra	LL39
LL37:

	incw	__main_lend-14
	__ldw	__main_lend-22
	__addwi	18
	__stw	__main_lend-22
	__lbra	LL36
LL38:

	__ldw	__main_lend-22
	__addwi	17
	__ldub_p
	__tstw
	__lbeqn	LL40
	__ldw	__main_lend-14
	  call	_spr_set
	__ldw	_soldierFrame
	  call	_spr_pattern
LL40:

	__lbra	LL37
LL39:

	__stwi	__main_lend-14, 4
	__stwi	__main_lend-22, _armyTwo
LL41:

	__ldw	__main_lend-14
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbnen	LL43
	__lbra	LL44
LL42:

	incw	__main_lend-14
	__ldw	__main_lend-22
	__addwi	18
	__stw	__main_lend-22
	__lbra	LL41
LL43:

	__ldw	__main_lend-22
	__addwi	17
	__ldub_p
	__tstw
	__lbeqn	LL45
	__ldw	__main_lend-14
	  call	_spr_set
	__ldw	_soldierFrame
	  call	_spr_pattern
	__ldw	__main_lend-22
	  call	_soldier_state_machine
LL45:

	__lbra	LL42
LL44:

	  call	_satb_update
	__lbra	LL34
LL35:

LL23:

	  rts
	.endp
	.data
	.bss
	__main_loc: .ds 30
	__main_lend:
	.code

	.proc _spr_make
	__pushw
	__ldw_s	14
	  call	_spr_set
	__ldw_s	12
	  call	_spr_x
	__ldw_s	10
	  call	_spr_y
	__ldw_s	8
	  call	_spr_pattern
	__ldw_s	6
	  stx	__al
	__ldw_s	4
	  call	_spr_ctrl.2
	__ldw_s	2
	  call	_spr_pal
	__ldw_s	0
	  call	_spr_pri
LL46:

	__addmi	16,__stack
	  rts
	.endp

	.proc _populate_army
	__pushw
	__ldw_s	0
	__stw	__populate_army_lend-2
LL48:

	__ldw	__populate_army_lend-2
	__pushw
	__ldw_s	4
	__addw_s	2
	  jsr	lt
	__lbnen	LL50
	__lbra	LL51
LL49:

	incw	__populate_army_lend-2
	__ldw_s	12
	__addwi	18
	__stw_s	12
	__lbra	LL48
LL50:

	__ldw	__populate_army_lend-2
	__pushw
	__ldw_s	14
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__andwi	127
	__aslwi	5
	__pushw
	__ldw_s	16
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	128
	  jsr	sdiv
	__aslwi	5
	__pushw
	__ldw_s	14
	__pushw
	__ldw	__populate_army_lend-2
	__pushw
	__ldw_s	20
	  jsr	smul
	__addws
	__pushw
	__ldwi	185
	__pushw
	__ldwi	17
	__pushw
	__ldw_s	18
	__pushw
	__ldwi	1
	  call	_spr_make
	__ldw_s	4
	__tstw
	__lbeq	LL52
	__ldwi	8
	  stx	__al
	__ldwi	8
	  call	_spr_ctrl.2
LL52:

	__ldw_s	8
	__pushw
	__ldw	__populate_army_lend-2
	__pushw
	__ldw_s	14
	  jsr	smul
	__addws
	__stw	__di
	__farptr	_attack,__bl,__si
	__ldw_s	10
	__stw	__cx
	  call	_load_vram.3
	__lbra	LL49
LL51:

LL47:

	__addmi	14,__stack
	  rts
	.endp
	.data
	.bss
	__populate_army_loc: .ds 2
	__populate_army_lend:
	.code

	.proc _find_nearest_opponent
	__pushw
	__stwi	__find_nearest_opponent_lend-2, 0
	__stwi	__find_nearest_opponent_lend-4, 0
	__stwi	__find_nearest_opponent_lend-6, 0
	__stwi	__find_nearest_opponent_lend-8, 5120
	__stwz	__find_nearest_opponent_lend-10
	__stwi	__find_nearest_opponent_lend-2, 0
LL54:

	__ldw	__find_nearest_opponent_lend-2
	__pushw
	__ldub	_current_opp_army_size
	  jsr	lt
	__lbnen	LL56
	__lbra	LL57
LL55:

	incw	__find_nearest_opponent_lend-2
	__ldw_s	0
	__addwi	18
	__stw_s	0
	__lbra	LL54
LL56:

	__ldw_s	0
	__addwi	17
	__ldub_p
	__tstw
	__lbeqn	LL59
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_is_opp_adjacent
	__notw
LL59:

	__tstw
	__lbeq	LL58
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__find_nearest_opponent_lend-4
	__stw	<__temp
	__ldw_s	2
	  jsr	gtzp
	__lbeqn	LL60
	__ldw	__find_nearest_opponent_lend-4
	__pushw
	__ldw_s	4
	__subws
	__stw	__find_nearest_opponent_lend-6
	__lbran	LL61
LL60:

	__ldw_s	2
	__subw	__find_nearest_opponent_lend-4
	__stw	__find_nearest_opponent_lend-6
LL61:

	__ldw	__find_nearest_opponent_lend-6
	__stw	<__temp
	__ldw	__find_nearest_opponent_lend-8
	  jsr	ltzp
	__lbeqn	LL62
	__ldw	__find_nearest_opponent_lend-6
	__stw	__find_nearest_opponent_lend-8
	__ldw	__find_nearest_opponent_lend-4
	__stw	__find_nearest_opponent_lend-10
LL62:

LL58:

	__lbra	LL55
LL57:

	__ldw	__find_nearest_opponent_lend-10
LL53:

	__addmi	4,__stack
	  rts
	.endp
	.data
	.bss
	__find_nearest_opponent_loc: .ds 10
	__find_nearest_opponent_lend:
	.code

	.proc _move_to
	__pushw
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__move_to_lend-10
	__ldw_s	2
	  call	_get_y_from_pos
	__stw	__move_to_lend-2
	__ldw_s	2
	  call	_get_x_from_pos
	__stw	__move_to_lend-4
	__ldw	__move_to_lend-10
	  call	_get_y_from_pos
	__stw	__move_to_lend-6
	__ldw	__move_to_lend-10
	  call	_get_x_from_pos
	__stw	__move_to_lend-8
	__ldw	__move_to_lend-4
	__stw	<__temp
	__ldw	__move_to_lend-8
	  jsr	ltzp
	__lbeqn	LL65
	__ldw	__move_to_lend-10
	__subwi	1
	__stw	__move_to_lend-10
	__addwi	1
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	0
LL65:

	__tstw
	__lbeq	LL64
	__ldw	__move_to_lend-10
	  call	_can_move_left
	__cmpwi_eq	1
	__lbeq	LL66
	__ldwi	_grid
	__addw	__move_to_lend-10
	__stbip	0
	__ldw_s	0
	__addwi	4
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
	__stw	__move_to_lend-10
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stw	<__ptr
	__ldw	_current_army_id
	__stbp	__ptr
	__ldw_s	0
	__addwi	12
	__stbip	1
	__ldw_s	0
	__addwi	14
	__stbip	32
	__ldw_s	0
	__addwi	13
	__stbip	3
LL66:

	__lbra	LL67
LL64:

	__ldw	__move_to_lend-2
	__stw	<__temp
	__ldw	__move_to_lend-6
	  jsr	ltzp
	__lbeqn	LL69
	__ldw	__move_to_lend-10
	__subwi	128
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	0
LL69:

	__tstw
	__lbeq	LL68
	__ldw	__move_to_lend-10
	  call	_can_move_up
	__cmpwi_eq	1
	__lbeq	LL70
	__ldwi	_grid
	__addw	__move_to_lend-10
	__stbip	0
	__ldw_s	0
	__addwi	4
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__subwi	128
	__stwps
	__stw	__move_to_lend-10
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stw	<__ptr
	__ldw	_current_army_id
	__stbp	__ptr
	__ldw_s	0
	__addwi	12
	__stbip	1
	__ldw_s	0
	__addwi	14
	__stbip	32
	__ldw_s	0
	__addwi	13
	__stbip	0
LL70:

	__lbra	LL71
LL68:

	__ldw	__move_to_lend-4
	__stw	<__temp
	__ldw	__move_to_lend-8
	  jsr	gtzp
	__lbeqn	LL73
	__ldw	__move_to_lend-10
	incw	__move_to_lend-10
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	0
LL73:

	__tstw
	__lbeq	LL72
	__ldw	__move_to_lend-10
	  call	_can_move_right
	__cmpwi_eq	1
	__lbeq	LL74
	__ldwi	_grid
	__addw	__move_to_lend-10
	__stbip	0
	__ldw_s	0
	__addwi	4
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__stw	__move_to_lend-10
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stw	<__ptr
	__ldw	_current_army_id
	__stbp	__ptr
	__ldw_s	0
	__addwi	12
	__stbip	1
	__ldw_s	0
	__addwi	14
	__stbip	32
	__ldw_s	0
	__addwi	13
	__stbip	1
LL74:

	__lbra	LL75
LL72:

	__ldw	__move_to_lend-2
	__stw	<__temp
	__ldw	__move_to_lend-6
	  jsr	gtzp
	__lbeqn	LL77
	__ldw	__move_to_lend-10
	__addwi	128
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	0
LL77:

	__tstw
	__lbeq	LL76
	__ldw	__move_to_lend-10
	  call	_can_move_down
	__cmpwi_eq	1
	__lbeq	LL78
	__ldwi	_grid
	__addw	__move_to_lend-10
	__stbip	0
	__ldw_s	0
	__addwi	4
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__addwi	128
	__stwps
	__stw	__move_to_lend-10
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stw	<__ptr
	__ldw	_current_army_id
	__stbp	__ptr
	__ldw_s	0
	__addwi	12
	__stbip	1
	__ldw_s	0
	__addwi	14
	__stbip	32
	__ldw_s	0
	__addwi	13
	__stbip	2
LL78:

LL76:

LL75:

LL71:

LL67:

LL63:

	__addmi	4,__stack
	  rts
	.endp
	.data
	.bss
	__move_to_loc: .ds 12
	__move_to_lend:
	.code

	.proc _get_y_from_pos
	__pushw
	__ldw_s	0
	__pushw
	__ldwi	128
	  jsr	sdiv
LL79:

	__addmi	2,__stack
	  rts
	.endp

	.proc _get_x_from_pos
	__pushw
	__ldw_s	0
	__andwi	127
LL80:

	__addmi	2,__stack
	  rts
	.endp

	.proc _tick
	incw	_tic
	__ldw	_tic
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL82
	__ldwi	0
	__stw	_tic
	incw	_frame
	__ldw	_soldierFrame
	__addwi	256
	__stw	_soldierFrame
	__ldw	_altFrame
	__addwi	256
	__stw	_altFrame
LL82:

	__ldw	_frame
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeqn	LL83
	__ldwi	0
	__stw	_frame
	__ldwi	20480
	__stw	_soldierFrame
	__ldwi	22528
	__stw	_altFrame
LL83:

LL81:

	  rts
	.endp

	.proc _controls
	__ldwi	0
	  call	_joy
	__stw	_j1
	__andwi	128
	__tstw
	__lbeq	LL85
	__ldw	_sx
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__lbeq	LL86
	__ldw	_xOffset
	__addwi	2
	__stw	_xOffset
	__ldw	_sx
	__subwi	2
	__stw	_sx
	__andwi	1023
	__stw	_sx
	__ldwi	0
	__pushw
	__ldw	_sx
	__asrwi	1
	__pushw
	__ldw	_sy
	__asrwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	223
	__pushw
	__ldwi	192
	  call	_scroll
LL86:

LL85:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL87
	__ldw	_sx
	__stw	<__temp
	__ldwi	1022
	  jsr	ltzp
	__lbeq	LL88
	__ldw	_xOffset
	__subwi	2
	__stw	_xOffset
	__ldw	_sx
	__addwi	2
	__stw	_sx
	__andwi	1023
	__stw	_sx
	__ldwi	0
	__pushw
	__ldw	_sx
	__asrwi	1
	__pushw
	__ldw	_sy
	__asrwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	223
	__pushw
	__ldwi	192
	  call	_scroll
LL88:

LL87:

	__ldw	_j1
	__andwi	16
	__tstw
	__lbeq	LL89
	__ldw	_sy
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__lbeq	LL90
	__ldw	_yOffset
	__addwi	2
	__stw	_yOffset
	__ldw	_sy
	__subwi	2
	__stw	_sy
	__andwi	511
	__stw	_sy
	__ldwi	0
	__pushw
	__ldw	_sx
	__asrwi	1
	__pushw
	__ldw	_sy
	__asrwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	223
	__pushw
	__ldwi	192
	  call	_scroll
LL90:

LL89:

	__ldw	_j1
	__andwi	64
	__tstw
	__lbeq	LL91
	__ldw	_sy
	__stw	<__temp
	__ldwi	511
	  jsr	ltzp
	__lbeq	LL92
	__ldw	_yOffset
	__subwi	2
	__stw	_yOffset
	__ldw	_sy
	__addwi	2
	__stw	_sy
	__andwi	511
	__stw	_sy
	__ldwi	0
	__pushw
	__ldw	_sx
	__asrwi	1
	__pushw
	__ldw	_sy
	__asrwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	223
	__pushw
	__ldwi	192
	  call	_scroll
LL92:

LL91:

LL84:

	  rts
	.endp

	.proc _is_opp_adjacent
	__pushw
	__ldw_s	0
	__subwi	1
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	1
	__lbeqn	LL94
	__ldw_s	0
	__subwi	1
	__lbra	LL93
LL94:

	__ldw_s	0
	__addwi	1
	__addwi_sym	_grid
	__ldub_p
	__cmpwi_eq	1
	__lbeqn	LL95
	__ldw_s	0
	__addwi	1
	__lbran	LL93
LL95:

	__ldwi	0
LL93:

	__addmi	2,__stack
	  rts
	.endp

	.proc _soldier_state_machine
	__pushw
	__ldw_s	0
	__addwi	12
	__ldub_p
	__cmpwi_eq	0
	__lbeqn	LL97
	__ldw_s	0
	  call	_soldier_idle_state
LL97:

	__ldw_s	0
	__addwi	12
	__ldub_p
	__cmpwi_eq	1
	__lbeqn	LL98
	__ldw_s	0
	  call	_soldier_move_state
LL98:

	__ldw_s	0
	__addwi	12
	__ldub_p
	__cmpwi_eq	2
	__lbeqn	LL99
	__ldw_s	0
	  call	_soldier_attack_state
LL99:

	__ldw_s	0
	__addwi	12
	__ldub_p
	__cmpwi_eq	3
	__lbeqn	LL100
	__ldw_s	0
	  call	_soldier_die_state
LL100:

LL96:

	__addmi	2,__stack
	  rts
	.endp

	.proc _soldier_idle_state
	__pushw
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_is_opp_adjacent
	__tstw
	__lbeqn	LL102
	__ldw_s	0
	__addwi	12
	__stbip	2
	__ldw	__soldier_idle_state_lend-6
	  call	_free
	__lbra	LL103
LL102:

	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get_x_from_pos
	__stw	__soldier_idle_state_lend-2
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get_y_from_pos
	__stw	__soldier_idle_state_lend-4
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stbip	0
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get_path
	__stw	__soldier_idle_state_lend-6
	__ldw	__soldier_idle_state_lend-2
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__stw	<__ptr
	__ldwp	__ptr
	  jsr	gt
	__lbeqn	LL104
	__ldw_s	0
	__addwi	13
	__stbip	3
	__lbra	LL105
LL104:

	__ldw	__soldier_idle_state_lend-4
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	  jsr	gt
	__lbeqn	LL106
	__ldw_s	0
	__addwi	13
	__stbip	0
	__lbra	LL107
LL106:

	__ldw	__soldier_idle_state_lend-4
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	  jsr	lt
	__lbeqn	LL108
	__ldw_s	0
	__addwi	13
	__stbip	2
	__lbra	LL109
LL108:

	__ldw	__soldier_idle_state_lend-2
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__stw	<__ptr
	__ldwp	__ptr
	  jsr	lt
	__lbeqn	LL110
	__ldw_s	0
	__addwi	13
	__stbip	1
LL110:

LL109:

LL107:

LL105:

	__ldw_s	0
	__addwi	4
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__aslwi	7
	__pushw
	__ldw	__soldier_idle_state_lend-6
	__stw	<__ptr
	__ldwp	__ptr
	__addws
	__stwps
	__ldw_s	0
	__addwi	12
	__stbip	1
	__ldw_s	0
	__addwi	14
	__stbip	32
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stbip	2
	__ldw	__soldier_idle_state_lend-6
	  call	_free
LL103:

LL101:

	__addmi	2,__stack
	  rts
	.endp
	.data
	.bss
	__soldier_idle_state_loc: .ds 6
	__soldier_idle_state_lend:
	.code

	.proc _soldier_move_state
	__pushw
	__ldw_s	0
	__addwi	14
	__ldub_p
	__cmpwi_eq	0
	__lbeq	LL112
	__ldw_s	0
	__addwi	12
	__stbip	0
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	128
	  jsr	sdiv
	__aslwi	5
	  call	_spr_y
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__andwi	127
	__aslwi	5
	  call	_spr_x
LL112:

	__ldwi	LL113
	__pushw
	__ldw_s	2
	__addwi	13
	__ldub_p
	  jmp	___case
LL115:

	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	128
	  jsr	sdiv
	__aslwi	5
	__pushw
	__ldw_s	2
	__addwi	14
	__ldub_p
	__addws
	  call	_spr_y
	__ldw_s	0
	__addwi	14
	__pushw
	__ldub_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL114
LL116:

	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__andwi	127
	__aslwi	5
	__pushw
	__ldw_s	2
	__addwi	14
	__ldub_p
	__subws
	  call	_spr_x
	__ldw_s	0
	__addwi	14
	__pushw
	__ldub_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL114
LL117:

	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	128
	  jsr	sdiv
	__aslwi	5
	__pushw
	__ldw_s	2
	__addwi	14
	__ldub_p
	__subws
	  call	_spr_y
	__ldw_s	0
	__addwi	14
	__pushw
	__ldub_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL114
LL118:

	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__andwi	127
	__aslwi	5
	__pushw
	__ldw_s	2
	__addwi	14
	__ldub_p
	__addws
	  call	_spr_x
	__ldw_s	0
	__addwi	14
	__pushw
	__ldub_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL114
	__lbra	LL114
LL113:

	.dw	LL115,0,LL116,1,LL117,2,LL118,3
	.dw	0,LL114
LL114:

LL111:

	__addmi	2,__stack
	  rts
	.endp

	.proc _soldier_attack_state
	__pushw
	__ldw_s	0
	__addwi	6
	__pushw
	__stw	<__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__cmpwi_eq	24
	__lbeq	LL120
	__ldwi	__soldier_attack_state_lend-2
	  call	_rand
	__andwi	255
	__stw	__soldier_attack_state_lend-2
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	  call	_is_opp_adjacent
	__stw	__soldier_attack_state_lend-4
	__cmpwi_eq	0
	__lbeqn	LL121
	__ldw_s	0
	__addwi	6
	__stwip	0
	__ldw_s	0
	__addwi	12
	__stbip	0
	__lbra	LL119
LL121:

	__ldw	__soldier_attack_state_lend-4
	  call	_get_unit_from_position
	__stw	__soldier_attack_state_lend-6
	__ldw	__soldier_attack_state_lend-2
	__stw	<__temp
	__ldwi	190
	  jsr	gtzp
	__lbeqn	LL122
	__ldw	__soldier_attack_state_lend-6
	  call	_kill_unit
LL122:

	__ldw_s	0
	__addwi	6
	__stwip	0
	__ldw_s	0
	__addwi	12
	__stbip	0
	__ldw	__soldier_attack_state_lend-6
	  call	_free
LL120:

LL119:

	__addmi	2,__stack
	  rts
	.endp
	.data
	.bss
	__soldier_attack_state_loc: .ds 6
	__soldier_attack_state_lend:
	.code

	.proc _soldier_die_state
	__pushw
LL123:

	__addmi	2,__stack
	  rts
	.endp

	.proc _get_unit_from_position
	__pushw
	__stwz	__get_unit_from_position_lend-2
	__stwi	__get_unit_from_position_lend-4, _armyOne
LL125:

	__ldw	__get_unit_from_position_lend-2
	__stw	<__temp
	__ldwi	4
	  jsr	ltzp
	__lbnen	LL127
	__lbra	LL128
LL126:

	incw	__get_unit_from_position_lend-2
	__ldw	__get_unit_from_position_lend-4
	__addwi	18
	__stw	__get_unit_from_position_lend-4
	__lbra	LL125
LL127:

	__ldw	__get_unit_from_position_lend-4
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw_s	0
	  jsr	eqzp
	__lbeqn	LL129
	__ldw	__get_unit_from_position_lend-4
	__lbran	LL124
LL129:

	__lbra	LL126
LL128:

LL124:

	__addmi	2,__stack
	  rts
	.endp

	.proc _kill_unit
	__pushw
	__ldw_s	0
	__addwi	17
	__stbip	0
	__ldw_s	0
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__addwi_sym	_grid
	__stbip	0
	__ldw_s	0
	__addwi	4
	__stwip	0
LL130:

	__addmi	2,__stack
	  rts
	.endp

	.proc _can_move_up
	__pushw
	__ldw_s	0
	__stw	<__temp
	__ldwi	128
	  jsr	gtzp
	__lbeqn	LL133
	__ldw_s	0
	__subwi	128
	__addwi_sym	_grid
	__ldub_p
	__notw
LL133:

	__tstw
	__lbeqn	LL132
	__ldwi	1
	__lbran	LL131
	__lbran	LL134
LL132:

	__ldwi	0
	__lbran	LL131
LL134:

LL131:

	__addmi	2,__stack
	  rts
	.endp

	.proc _can_move_right
	__pushw
	__ldw_s	0
	  call	_get_x_from_pos
	__stw	<__temp
	__ldwi	128
	  jsr	ltzp
	__lbeqn	LL137
	__ldw_s	0
	__addwi	1
	__addwi_sym	_grid
	__ldub_p
	__notw
LL137:

	__tstw
	__lbeqn	LL136
	__ldwi	1
	__lbran	LL135
	__lbran	LL138
LL136:

	__ldwi	0
	__lbran	LL135
LL138:

LL135:

	__addmi	2,__stack
	  rts
	.endp

	.proc _can_move_left
	__pushw
	__ldw_s	0
	  call	_get_x_from_pos
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__lbeqn	LL141
	__ldw_s	0
	__subwi	1
	__addwi_sym	_grid
	__ldub_p
	__notw
LL141:

	__tstw
	__lbeqn	LL140
	__ldwi	1
	__lbran	LL139
	__lbran	LL142
LL140:

	__ldwi	0
	__lbran	LL139
LL142:

LL139:

	__addmi	2,__stack
	  rts
	.endp

	.proc _can_move_down
	__pushw
	__ldw_s	0
	__stw	<__temp
	__ldwi	20
	  jsr	ltzp
	__lbeqn	LL145
	__ldw_s	0
	__addwi	128
	__addwi_sym	_grid
	__ldub_p
	__notw
LL145:

	__tstw
	__lbeqn	LL144
	__ldwi	1
	__lbran	LL143
	__lbran	LL146
LL144:

	__ldwi	0
	__lbran	LL143
LL146:

LL143:

	__addmi	2,__stack
	  rts
	.endp

	.proc _get_neighbors
	__pushw
	__stwz	__get_neighbors_lend-4
	__ldw_s	2
	__subwi	1
	__stw	<__temp
	__ldwi	-1
	  jsr	gtzp
	__lbeq	LL148
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__pushw
	__ldw_s	4
	__subwi	1
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	4
	__stw	<__ptr
	__ldw_s	2
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	6
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stwip	1
	__ldw	__get_neighbors_lend-4
	incw	__get_neighbors_lend-4
LL148:

	__ldw_s	0
	__subwi	1
	__stw	<__temp
	__ldwi	-1
	  jsr	gtzp
	__lbeq	LL149
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__stw	<__ptr
	__ldw_s	2
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__pushw
	__ldw_s	2
	__subwi	1
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	4
	__stw	<__ptr
	__ldw_s	2
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	6
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stwip	1
	__ldw	__get_neighbors_lend-4
	incw	__get_neighbors_lend-4
LL149:

	__ldw_s	0
	__addwi	1
	__stw	<__temp
	__ldwi	10
	  jsr	ltzp
	__lbeq	LL150
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__pushw
	__ldw_s	4
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	4
	__pushw
	__ldw_s	4
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	6
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stwip	1
	__ldw	__get_neighbors_lend-4
	incw	__get_neighbors_lend-4
LL150:

	__ldw_s	2
	__addwi	1
	__stw	<__temp
	__ldwi	10
	  jsr	ltzp
	__lbeq	LL151
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__pushw
	__ldw_s	4
	__addwi	1
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	4
	__stw	<__ptr
	__ldw_s	2
	__stwp	__ptr
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	6
	__pushw
	__ldw_s	2
	__stwps
	__ldw	__get_neighbors_lend-4
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stwip	1
	__ldw	__get_neighbors_lend-4
	incw	__get_neighbors_lend-4
LL151:

	__ldw	__get_neighbors_lend-4
	__subwi	1
	__stw	__get_neighbors_lend-2
LL152:

	__ldw	__get_neighbors_lend-2
	__stw	<__temp
	__ldwi	3
	  jsr	ltzp
	__lbnen	LL154
	__lbra	LL155
LL153:

	__ldw	__get_neighbors_lend-2
	incw	__get_neighbors_lend-2
	__lbra	LL152
LL154:

	__ldw	__get_neighbors_lend-2
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stwip	0
	__lbra	LL153
LL155:

	__ldw	__get_neighbors_lend-4
	__subwi	1
LL147:

	__addmi	4,__stack
	  rts
	.endp

	.proc _get_path
	__pushw
	__stwi	__get_path_lend-1012, 0
	__stwi	__get_path_lend-1014, 0
	__stwi	__get_path_lend-1016, 0
	__stwi	__get_path_lend-1018, 1
	__stwz	__get_path_lend-1020
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__pushw
	__ldw_s	2
	  call	_get_x_from_pos
	__stwps
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__pushw
	__ldw_s	2
	  call	_get_y_from_pos
	__stwps
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	4
	__pushw
	__ldw_s	2
	  call	_get_x_from_pos
	__stwps
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	6
	__pushw
	__ldw_s	2
	  call	_get_y_from_pos
	__stwps
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	8
	__stwip	1
LL157:

	__ldw	_map_counter
	__mulwi	10
	__addwi_sym	_map
	__addwi	8
	__stw	<__ptr
	__ldwp	__ptr
	__cmpwi_eq	1
	__lbeqn	LL159
	__ldw	__get_path_lend-1018
	__cmpwi_eq	1
LL159:

	__tstw
	__lbeq	LL158
	__ldwi	__get_path_lend-1016
	__pushw
	__ldw	_map_counter
	__mulwi	10
	__addwi_sym	_map
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_map_counter
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get_neighbors
	__stwps
	__stwi	__get_path_lend-1014, 0
LL160:

	__ldw	__get_path_lend-1014
	__stw	<__temp
	__ldw	__get_path_lend-1016
	  jsr	lezp
	__lbeq	LL161
	__ldwi	__get_path_lend-1012
	__pushw
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__aslwi	7
	__pushw
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__stw	<__ptr
	__ldwp	__ptr
	__addws
	__stwps
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__get_path_lend-1004
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__get_path_lend-1006
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__get_path_lend-1008
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	6
	__stw	<__ptr
	__ldwp	__ptr
	__stw	__get_path_lend-1010
	__ldw	__get_path_lend-1014
	__mulwi	10
	__addwi_sym	_neighbors
	__addwi	8
	__stw	<__ptr
	__ldwp	__ptr
	__cmpwi_eq	1
	__lbeq	LL162
	__ldwi	_grid
	__addw	__get_path_lend-1012
	__ldub_p
	__cmpwi_eq	2
	__lbnen	LL164
	__ldwi	_grid
	__addw	__get_path_lend-1012
	__ldub_p
	__cmpwi_eq	1
LL164:

	__tstw
	__lbeqn	LL163
	__lbra	LL165
LL163:

	__ldwi	_grid
	__addw	__get_path_lend-1012
	__ldub_p
	__cmpwi_eq	0
	__lbeq	LL166
	__ldw	__get_path_lend-1004
	__pushw
	__ldw	__get_path_lend-1006
	__pushw
	__ldw	__get_path_lend-1008
	__pushw
	__ldw	__get_path_lend-1010
	  call	_put_visited
	__lbra	LL167
LL166:

	__ldw	__get_path_lend-1004
	__pushw
	__ldw	__get_path_lend-1006
	__pushw
	__ldw	__get_path_lend-1008
	__pushw
	__ldw	__get_path_lend-1010
	  call	_put_visited
	__stwz	__get_path_lend-1018
	__stwi	__get_path_lend-1014, 10
LL167:

LL165:

LL162:

	__ldw	__get_path_lend-1014
	incw	__get_path_lend-1014
	__lbra	LL160
LL161:

	__ldw	_map_counter
	incw	_map_counter
	__lbra	LL157
LL158:

	__ldwi	__get_path_lend-1002
	__pushw
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get
	__stwps
LL168:

	__ldw	__get_path_lend-1002
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw	_map
	  jsr	nezp
	__lbnen	LL170
	__ldw	__get_path_lend-1002
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw	_map+2
	  jsr	nezp
LL170:

	__tstw
	__lbeq	LL169
	__ldw	__get_path_lend-1020
	__mulwi	10
	__addwi_sym	__get_path_lend-1000
	__pushw
	__ldw	__get_path_lend-1002
	__stw	<__ptr
	__ldwp	__ptr
	__stwps
	__ldw	__get_path_lend-1020
	incw	__get_path_lend-1020
	__mulwi	10
	__addwi_sym	__get_path_lend-1000
	__addwi	2
	__pushw
	__ldw	__get_path_lend-1002
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__stwps
	__ldw	__get_path_lend-1002
	__addwi	4
	__stw	<__ptr
	__ldwp	__ptr
	__pushw
	__ldw	__get_path_lend-1002
	__addwi	6
	__stw	<__ptr
	__ldwp	__ptr
	  call	_get
	__stw	__get_path_lend-1002
	__lbra	LL168
LL169:

	__ldw	__get_path_lend-1002
	  call	_free
	__ldwi	0
	__stw	_map_counter
	__ldwi	0
	__stw	_map_size
	__ldwi	__get_path_lend-1012
	__pushw
	__ldw	__get_path_lend-1020
	__subwi	1
	__mulwi	10
	__addwi_sym	__get_path_lend-1000
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__aslwi	7
	__pushw
	__ldw	__get_path_lend-1020
	__subwi	1
	__mulwi	10
	__addwi_sym	__get_path_lend-1000
	__stw	<__ptr
	__ldwp	__ptr
	__addws
	__stwps
	__ldw	__get_path_lend-1020
	__subwi	1
	__mulwi	10
	__addwi_sym	__get_path_lend-1000
LL156:

	__addmi	2,__stack
	  rts
	.endp
	.data
	.bss
	__get_path_loc: .ds 1020
	__get_path_lend:
	.code

	.proc _put_visited
	__pushw
	__stwi	__put_visited_lend-2, 0
	__stwz	__put_visited_lend-4
	__stwi	__put_visited_lend-2, 0
LL172:

	__ldw	__put_visited_lend-2
	__pushw
	__ldw	_map_size
	__addwi	1
	  jsr	lt
	__lbnen	LL174
	__lbra	LL175
LL173:

	__ldw	__put_visited_lend-2
	incw	__put_visited_lend-2
	__lbra	LL172
LL174:

	__ldw	__put_visited_lend-2
	__mulwi	10
	__addwi_sym	_map
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw_s	6
	  jsr	eqzp
	__lbeq	LL177
	__ldw	__put_visited_lend-2
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw_s	4
	  jsr	eqzp
LL177:

	__tstw
	__lbeqn	LL176
	__ldwi	0
	__lbra	LL171
LL176:

	__lbra	LL173
LL175:

	incw	_map_size
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__pushw
	__ldw_s	8
	__stwps
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__stw	<__ptr
	__ldw_s	4
	__stwp	__ptr
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	4
	__stw	<__ptr
	__ldw_s	2
	__stwp	__ptr
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	6
	__stw	<__ptr
	__ldw_s	0
	__stwp	__ptr
	__ldw	_map_size
	__mulwi	10
	__addwi_sym	_map
	__addwi	8
	__stwip	1
	__ldwi	1
LL171:

	__addmi	8,__stack
	  rts
	.endp

	.proc _get
	__pushw
	__stwz	__get_lend-2
	__stwi	__get_lend-2, 0
LL179:

	__ldw	__get_lend-2
	__pushw
	__ldw	_map_size
	__addwi	1
	  jsr	lt
	__lbnen	LL181
	__lbra	LL182
LL180:

	__ldw	__get_lend-2
	incw	__get_lend-2
	__lbra	LL179
LL181:

	__ldw	__get_lend-2
	__mulwi	10
	__addwi_sym	_map
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw_s	2
	  jsr	eqzp
	__lbeq	LL184
	__ldw	__get_lend-2
	__mulwi	10
	__addwi_sym	_map
	__addwi	2
	__stw	<__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldw_s	0
	  jsr	eqzp
LL184:

	__tstw
	__lbeqn	LL183
	__ldw	__get_lend-2
	__mulwi	10
	__addwi_sym	_map
	__lbran	LL178
LL183:

	__lbra	LL180
LL182:

	__ldwi	-1
LL178:

	__addmi	4,__stack
	  rts
	.endp


	.bss
_msys:		.ds	4
_grid:		.ds	2000
_map:		.ds	2000
_neighbors:		.ds	40
_armyOne:		.ds	72
_armyTwo:		.ds	36
_opp_army:		.ds	2


;0 error(s) in compilation
;	literal pool:0
;	constant pool:0
;	global pool:112
;	Macro pool:91
leaf_loc: .ds 8
____compact_lend:
__free_lend:
__get_unit_from_position_lend:
__get_neighbors_lend:
__put_visited_lend:
__get_lend:
huc_data:
___huc_data:
_sprite_memory_start:	.ds	2
_sprite_size:	.ds	2
_army_one_x_start:	.ds	2
_army_one_y_start:	.ds	2
_army_two_x_start:	.ds	2
_army_two_y_start:	.ds	2
_opp:	.ds	2
_current_army_id:	.ds	2
_army_one_current_size:	.ds	1
_army_two_current_size:	.ds	1
_current_opp_army_size:	.ds	1
_map_counter:	.ds	2
_map_size:	.ds	2
_soldierFrame:	.ds	2
_altFrame:	.ds	2
_frame:	.ds	2
_tic:	.ds	2
_sx:	.ds	2
_sy:	.ds	2
_yOffset:	.ds	2
_j1:	.ds	2
_xOffset:	.ds	2
huc_data_end:
___huc_data_end:
__heap_start:
	.data
	.bank CONST_BANK
huc_rodata:
___huc_rodata:

.dw	20480

.dw	2048

.dw	0

.dw	0

.dw	0

.dw	0

.dw	0

.dw	0

.db	4

.db	2

.db	0

.dw	0

.dw	0

.dw	20480

.dw	22528

.dw	20480

.dw	0

.dw	0

.dw	0

.dw	0

.dw	0

.dw	0
huc_rodata_end:
___huc_rodata_end:
